### ISSUE TITLE
publicsuffix is deprecated

### ISSUE THREAD

**Issue by BastianZim** [dhs-ncats/trustymail#129]
# 💡 Summary #

What is the work, as a high-level summary?

Change publicsuffix to a different package

## Motivation and context ##

Deprecated packages can introduce security risks

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Package is changed

Ref: https://pypi.org/project/publicsuffix/

**Comment by jsf9k** [comment]
I think #128 already addresses this issue.

**Comment by BastianZim** [comment]
Ahh, I was only searching issues – thanks!

I'll keep it open since you linked the PR but feel free to close it as well.
