### ISSUE TITLE
Empty string fields that should probably be null

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/trustymail#22]
There are some empty strings in some fields that should probably be `null`:

```
    "Domain Supports SMTP": false,
    "Domain Supports SMTP Results": "",
    "Domain Supports STARTTLS": false,
    "Domain Supports STARTTLS Results": "",
...
```

I assume these values aren't meant to represent literal empty strings. If a domain doesn't support SMTP, I would expect a description of its SMTP support to be `null`.

**Comment by jsf9k** [comment]
I'll change them to null if there are no entries.
