### ISSUE TITLE
Non-ASCII characters in DNS makes trustymail crash

### ISSUE THREAD

**Issue by byeskille** [dhs-ncats/trustymail#26]
This is probably a mix of domains not following standards and handling of errors in `trustymail`.

I see in testing that `trustymail` crashes completely when finding non-ASCII characters in DNS.

See example with testing the domain aigecala.no:
```
python -m trustymail.cli --smtp-timeout=15 --debug aigecala.no
[aigecala.no]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/trustymail/trustymail/cli.py", line 140, in <module>
    main()
  File "/home/trustymail/trustymail/cli.py", line 93, in main
    scan_types))
  File "/home/trustymail/trustymail/trustymail.py", line 295, in scan
    spf_scan(domain)
  File "/home/trustymail/trustymail/trustymail.py", line 175, in spf_scan
    record_text = record_to_str(record)
  File "/home/trustymail/trustymail/trustymail.py", line 306, in record_to_str
    record = record.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 1: invalid continuation byte
```

This domain does not have a MX record, but `trustymail` seems to still look for a SPF record and then finds this:
`aigecala.no.		86400	IN	TXT	"S\225mi die?ala\168 \225ige?\225la"
`
It seems to be some kind of text in the Sami language set as a TXT record.

When trying to scan many domains from a source csv-file `trustymail` could maybe log these as errors and not stop the entire scan?

**Comment by jsf9k** [comment]
Thanks for the issue, @byeskille!  I should be able to catch the exception, log it, and keep going.  I'll make the change once pull request 25 gets merged.

**Comment by jsf9k** [comment]
@byeskille, what version of trustymail are you using?  The offending exception does not appear to be thrown any longer since we switched from using `py3dns` to `dnspython` in #25.  At least I'm not seeing it with the code currently in `master`.

Are you able to test with the code currently in `master` and let me know if you're still seeing an issue?  Or do you need a new version pushed to PyPI so that you can install via `pip`?

**Comment by byeskille** [comment]
@jsf9k I have been cloning this repo and running `pip install -r requirements.txt` 
So after updating from the repo and doing the install once again it is working!

The mentioned domain above no longer fails hard, and I have tested a couple more I earlier experienced crashes for with no problems.

I have now started a scan of a larger domain list csv with varying data quality, and can report back my experiences later.

**Comment by jsf9k** [comment]
That's great, @byeskille!  I look forward to hearing how your testing goes.  I'll leave the issue open for now.

**Comment by jsf9k** [comment]
@byeskille, just checking in to see how your testing went.

**Comment by byeskille** [comment]
Sorry for the late update. I can report that my two large scans with a total exceeding 10.000 domains went through without crashing. So thanks!

**Comment by jsf9k** [comment]
Excellent! :+1:
