### ISSUE TITLE
Suggest using a gitflow workflow with master and develop branches

### ISSUE THREAD

**Issue by jsf9k** [dhs-ncats/trustymail#36]
Given that we're actually releasing to PyPI, I think it makes sense to use a gitflow workflow (see [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) and [here](http://nvie.com/posts/a-successful-git-branching-model/)) with both `master` and `develop` branches.  That way the `master` branch will always contain the code that has been released to PyPI and the `develop` branch will always contain the code that is intended to go into the next release.  Work that is still in progress will live in feature branches, as it does right now.  Those branches will just go into `develop` before they make their way into `master` and get released.

It also simplifies our versioning a little bit, because the `master` branch will always have a version of the form `x.y.z`, while the `develop` branch will have a version of the form `x.y.z-dev`.  We won't have to switch back and forth.

I'm happy to implement this change, but I wanted to make sure that any other active developers are on board first.

**Comment by h-m-f-t** [comment]
I haven't read those links yet, but I think the suggestion is quality 👍

**Comment by IanLee1521** [comment]
👍 Sounds good to me! If so, I would suggest we do the same with pshtt and possibly domain-scan (if @konklone is on board as well).

**Comment by jsf9k** [comment]
I agree that we should do the same for `pshtt`.  I also like the idea of only allowing changes to `master` and `develop` via pull request - no direct commits.  That way there is at least some documentation for any changes that went into a release.  Thoughts about that?

**Comment by konklone** [comment]
There's a GitHub setting to do just that, in protected branches. I agree and recommend it.

For domain-scan, there aren't yet a concept of "releases" there, but if it gets to that point, splitting branches like that is what I would do.

**Comment by jsf9k** [comment]
I created the `develop` branch, and `develop` and `master` are now protected branches.

**Comment by IanLee1521** [comment]
@jsf9k -- You may also want to make the develop branch the default, instead of master.

**Comment by jsf9k** [comment]
I just made the same changes for pshtt as well.

@IanLee1521, the default branch for both repos should now be `develop`.

**Comment by IanLee1521** [comment]
Confirmed. Thanks!
