### ISSUE TITLE
Consider impact of making SERVFAIL responses Live = False

### ISSUE THREAD

**Issue by h-m-f-t** [dhs-ncats/trustymail#40]
Of DNS responses, the only one trustymail says indicates a domain is not Live is when an NXDOMAIN answer is received. SERVFAIL is the all purpose "something went wrong" response, indicative of misconfiguration or other error at the authoritative name server. While a domain may not always SERVFAIL, if the error is received at scan time that domain is, for all intents and purposes, _not available_: it might as well not exist. If it doesn't exist, there's no action we can incentivize a domain owner to take and it should be marked a Live = False (though we should log and report on a SERVFAIL).

Currently, 37 federal .gov domains respond with SERVFAIL:

> abmcscholar.gov
> biosecurityboard.gov
> chemsafety.gov
> citizencorps.gov
> citizencosponsors.gov
> clinicaltrial.gov
> consumerfinancialbureau.gov
> directoasucuenta.gov
> disability.gov
> eguardian.gov
> employer.gov
> energysaver.gov
> energysavers.gov
> eta-find.gov
> fedspending.gov
> fhfb.gov
> frc.gov
> fttesttwai.gov
> godirect.gov
> hirevets.gov
> ioss.gov
> ipp.gov
> kapl.gov
> learnatf.gov
> medicalreservecorps.gov
> medline.gov
> nationalmall.gov
> ncd.gov
> nwbc.gov
> ofheo.gov
> pix.gov
> safetyvideos.gov
> sigar.gov
> techtrack.gov
> trainingproviderresults.gov
> treasuryauction.gov
> verifypayment.gov

**Comment by jsf9k** [comment]
@h-m-f-t, where are you seeing the 37 agencies that respond with `SERVFAIL`.  The most recent tmail scan has none, so I need to look at the `results.csv` file from whatever collection you got the data from.

**Comment by h-m-f-t** [comment]
Sorry, I should have mentioned how I got those results. The data above comes from running `host` over the second-level .govs in [current-federal.csv](https://github.com/GSA/data/blob/master/dotgov-domains/current-federal.csv). Something like:

```bash
for i in $(cut -d, -f1 current-federal.csv); do host $i|grep "SERVFAIL";done
```
nets me these domains:
>abmcscholar.gov
biosecurityboard.gov
chemsafety.gov
citizencorps.gov
citizencosponsors.gov
clinicaltrial.gov
disability.gov
edpubs.gov
eguardian.gov
emergency-federal-register.gov
employer.gov
energysaver.gov
energysavers.gov
fedspending.gov
fhfb.gov
fsapubs.gov
fttesttwai.gov
hirevets.gov
ioss.gov
kapl.gov
learnatf.gov
medicalreservecorps.gov
medline.gov
nationalmall.gov
ofheo.gov
pix.gov
safetyvideos.gov
sigar.gov
techtrack.gov
trainingproviderresults.gov
verifypayment.gov
welcometousa.gov

**Comment by jsf9k** [comment]
@h-m-f-t, I have code to fix this, but to avoid merge conflicts I'd like to get @seanthegeek's pull request in first.

See [this branch](https://github.com/dhs-ncats/trustymail/tree/improvement/better_handling_of_servfail).
