### ISSUE TITLE
Check that a DMARC record includes a particular mailto: in rua flags

### ISSUE THREAD

**Issue by h-m-f-t** [dhs-ncats/trustymail#45]
[Now that the NCCIC reporting address is out](https://github.com/dhs-ncats/cyber.dhs.gov/pull/27), we need to validate that a domain's DMARC record includes `reports@dmarc.cyber.dhs.gov`. This should be an optional flag (maybe called `--mailto=`?) with true/false values in a key called "Mailto Mandate" (...or something better).

The BOD requires this address to be in `rua=`, not `ruf=`'s, so only `rua=`'s should be inspected.

This should work similar to how our `DMARC Policy` check works: If there's a DMARC record at the (sub)domain, the address should be in that `rua=`. If there's a DMARC records at the base domain, the address should be in that `rua=`. "Mailto Mandate" should be True when the address is present at the controlling DMARC record, whether at the domain directly or at the base domain.

**Comment by konklone** [comment]
I recommend using a transport-agnostic flag, since reporting URIs don't just have to be email, right?  And it's also aggregate reports only, not forensic reports.

So I might use something like `--aggregate-reports-to`, with the protocol in place like `--aggregate-reports-to=mailto:reports@dmarc.cyber.dhs.gov`, and have that validate that that URI is present among the `rua=` values.

**Comment by seanthegeek** [comment]
Also, consider that DMARC URIs may have size limits on the end of them. e.g. `!10m` when looking for the specific address.

Luckily, I included code that parses out the scheme/transport, address, and size limit in the [latest commits to my PR](https://github.com/dhs-ncats/trustymail/pull/44/files#diff-904039f72ed14591250159dda2248e70R295)!

**Comment by h-m-f-t** [comment]
@jsf9k @dav3r I'm happy with the approach @seanthegeek took in #44. Any reason we should keep this issue open?

**Comment by jsf9k** [comment]
It can be closed as far as I'm concerned.

**Comment by jsf9k** [comment]
It can be closed as far as I'm concerned.

**Comment by jsf9k** [comment]
It can be closed as far as I'm concerned.

**Comment by jsf9k** [comment]
It can be closed as far as I'm concerned.

**Comment by h-m-f-t** [comment]
Closing in favor of a dedicated aggregate report field, per #44.
