### ISSUE TITLE
TypeError: handle_syntax_error()

### ISSUE THREAD

**Issue by zer0Trac3** [dhs-ncats/trustymail#51]
line 433, in dmarc_scan
    handle_syntax_error("Error: The DMARC pct tag value must not be less than 100 "
TypeError: handle_syntax_error() missing 2 required positional arguments: 'domain' and 'error'

Running on Mac OSx Sierra using Python3.5 in virtualenv.

**Comment by jsf9k** [comment]
Thanks for the report, @zer0Trac3!  I will fix that right now.

**Comment by jsf9k** [comment]
@zer0Trac3, do happen to have a hostname that triggers the error you saw?  I want to test my change to make sure it works.
