### ISSUE TITLE
Install in virtualenv with python3!

### ISSUE THREAD

**Issue by refayathaque** [dhs-ncats/trustymail#63]
For help use : https://help.dreamhost.com/hc/en-us/articles/215489338-Installing-and-using-Python-s-virtualenv

And this for installing Python3 : https://help.dreamhost.com/hc/en-us/articles/115000218612-Installing-a-custom-version-of-Python

Please speak to this in the documentation.

Thanks!

**Comment by IanLee1521** [comment]
Hi @refayathaque  -- Are you saying that the documentation should state the `trustymail` should only be installed in a virtualenv? 

While that is generally a best practice of Python packages in general, it isn't strictly a requirement...

**Comment by jsf9k** [comment]
@refayathaque I think using virtualenv for Python development is pretty standard stuff.  That said, you're welcome to create a pull request containing some documentation about how to do that if you want.
