### ISSUE TITLE
Broken CSV Import

### ISSUE THREAD

**Issue by malvidin** [dhs-ncats/trustymail#81]
The import of domains from a CSV doesn't use the correct import.

`domains = trustymail.domain_list_from_csv(open(args['INPUT'][0]))`
    should be
`domains = tmail.domain_list_from_csv(open(args['INPUT'][0]))`

https://github.com/dhs-ncats/trustymail/blob/da98d8cd9a1e41817d10465e4e7da5c7c195c593/scripts/trustymail#L85

Traceback (most recent call last):
  File "./trustymail", line 179, in <module>
    main()
  File "./trustymail", line 85, in main
    domains = trustymail.domain_list_from_csv(open(args['INPUT'][0]))
AttributeError: module 'trustymail' has no attribute 'domain_list_from_csv'

**Comment by jsf9k** [comment]
Good catch, @malvidin!
