### ISSUE TITLE
Incorrect DMARC Check Error

### ISSUE THREAD

**Issue by malvidin** [dhs-ncats/trustymail#82]
[The RFC states in 6.6.3 item 4](https://tools.ietf.org/html/rfc7489#section-6.6.3) that: 
>    4.  Records that do not start with a "v=" tag that identifies the current version of DMARC are discarded.

The current check only looks at the number of results, not those that start with "v=" and the current DMARC version, "DMARC1".

I recommend inserting something similar to the following before line 352. Any subsequent error about the duplicate DMARC errors will be accurate.
`[ record for record in records if (record.to_text().startswith('"v=DMARC1;')) ]`

https://github.com/dhs-ncats/trustymail/blob/f3209130a930ab5efc4c199daf394f037703ed1a/trustymail/trustymail.py#L350

**Comment by jsf9k** [comment]
Another great catch, @malvidin!  Thank you!
