### ISSUE TITLE
DNS has no attribute Type

### ISSUE THREAD

**Issue by mvogelgesang** [dhs-ncats/trustymail#83]
I am having difficulty running trustymail against any domains and receiving a "AttributeError: module 'DNS' has no attribute 'Type'" error. The error below is the same 

**Background info:**
Macbook air
Using pyenv to manage Python versions
Python v3.6.5 
Built locally using tag v0.5.5

**Other workarounds attempted**
- Run against other versions of Python 3.4.0, 2.7.0
- Run against latest on develop (61aaee4)
- Install and run via `pip install trustymail`

**Output**
````
$ python scripts/trustymail gsa.gov
Traceback (most recent call last):
  File "scripts/trustymail", line 179, in <module>
    main()
  File "scripts/trustymail", line 76, in main
    import trustymail.trustymail as tmail
  File "/Users/me/Sites/trustymail/trustymail/trustymail.py", line 11, in <module>
    import spf
  File "/Users/me/.pyenv/versions/3.6.5/lib/python3.6/site-packages/spf.py", line 111, in <module>
    if not hasattr(DNS.Type, 'SPF'):
AttributeError: module 'DNS' has no attribute 'Type'
````

**Comment by h-m-f-t** [comment]
Thanks for the report, @mvogelgesang. This is a [known issue](https://github.com/dhs-ncats/trustymail/issues/41#issuecomment-355390394), caused because the macOS filesystem is case-insensitive (by default).

**Comment by mvogelgesang** [comment]
Thanks @h-m-f-t. Apologies, I must have overlooked it prior to creating the issue.

**Comment by jsf9k** [comment]
No worries, @mvogelgesang.  I'm closing this issue as a duplicate.
