### ISSUE TITLE
How to check for Strong Crypto?

### ISSUE THREAD

**Issue by refayathaque** [dhs-ncats/trustymail#86]
Hi guys,

First of all, thank you again for creating this amazing library, it's been making our work at HHS monitoring BOD-18-01 compliance so much easier.

We wanted to know how we could check for SSLv2, SSLv3, TLSv1.1 and 3DES and RC4 ciphers on SMTP servers. We are trying to use trustymail to get email BOD-18-01 compliance, but need to figure out how to do the Strong Crypto part of the assessment.

We have worked with SSLyze in the past, and we think it might work, but we're unsure if it is something that only scans Web servers and not SMTP servers. Any light on this would be greatly appreciated.

Thank you so much for your help!

**Comment by jsf9k** [comment]
Thanks for the encouraging words, @refayathaque!

We use [18F/domain-scan](https://github.com/18F/domain-scan) to scan the domain, and that in turn leverages [nabla-c0d3/sslyze](https://github.com/nabla-c0d3/sslyze/) to check for weak crypto.  So it sounds like you are in the right track.

**Comment by jsf9k** [comment]
I also learned about Bulma from your GitHub profile just now, so thanks for that :smiley:

**Comment by refayathaque** [comment]
Hi @jsf9k ! Sorry but we're still unclear about how exactly we can figure out what network configuration protocol is enabled/disabled in an email SMTP server. Do we have to change the port settings in SSLyze before doing the scan? Is there a special SSLyze function that is only used for email SMTP servers? Thank you so much for the guidance.

**Comment by jsf9k** [comment]
@refayathaque, you can see how 18F/domain-scan does it by looking [here](https://github.com/18F/domain-scan/blob/master/scanners/sslyze.py#L211-L220) and [here](https://github.com/18F/domain-scan/blob/master/scanners/sslyze.py#L433-L497).  I don't know if it is also possible from the `sslyze` command line.
